export const DUMMY_PRODUCTS = [
  {
    id: 1,
    name: "Peperoni",
    category: "Pizza",
    price: 3000,
    photo: "./images/Peperoni.jpg",
  },
  {
    id: 2,
    name: "Ananasov",
    category: "Pizza",
    price: 5000,
    photo: "images/Peperoni.jpg",
  },
  {
    id: 3,
    name: "Snkov",
    category: "Pizza",
    price: 4000,
    photo: "images/Peperoni.jpg",
  },
  {
    id: 4,
    name: "Suluguniov",
    category: "Pizza",
    price: 3500,
    photo: "images/Peperoni.jpg",
  },
  {
    id: 5,
    name: "Zeytunov",
    category: "Pizza",
    price: 2000,
    photo: "images/Peperoni.jpg",
  },
  {
    id: 6,
    name: "Coca-Cola",
    category: "Drinc",
    price: 500,
    photo: "./images/Drinc.jpg",
  },
  {
    id: 7,
    name: "Fanta",
    category: "Drinc",
    price: 700,
    photo: "images/Drinc.jpg",
  },
  {
    id: 8,
    name: "Sprite",
    category: "Drinc",
    price: 550,
    photo: "images/Drinc.jpg",
  },
  {
    id: 9,
    name: "Palpy",
    category: "Drinc",
    price: 800,
    photo: "images/Drinc.jpg",
  },
  {
    id: 10,
    name: "Sevan Anush",
    category: "Drinc",
    price: 2000,
    photo: "images/Drinc.jpg",
  },
  {
    id: 11,
    name: "Mirinda",
    category: "Drinc",
    price: 750,
    photo: "images/Drinc.jpg",
  },
  {
    id: 12,
    name: "Banan",
    category: "Fruits",
    price: 500,
    photo: "images/Fruits.png",
  },
  {
    id: 13,
    name: "Xndzor",
    category: "Fruits",
    price: 450,
    photo: "images/Fruits.png",
  },
  {
    id: 14,
    name: "Bal",
    category: "Fruits",
    price: 600,
    photo: "images/Fruits.png",
  },
  {
    id: 15,
    name: "Ciran",
    category: "Fruits",
    price: 200,
    photo: "images/Fruits.png",
  },
  {
    id: 16,
    name: "Narinj",
    category: "Fruits",
    price: 850,
    photo: "images/Fruits.png",
  },
  {
    id: 17,
    name: "Americano",
    category: "Coffe",
    price: 800,
    photo: "images/Coffe.png",
  },
  {
    id: 18,
    name: "Capuchino",
    category: "Coffe",
    price: 500,
    photo: "images/Coffe.png",
  },
  {
    id: 19,
    name: "Expresso",
    category: "Coffe",
    price: 950,
    photo: "images/Coffe.png",
  },
];
